.segment "ROM0"
Game0001_c:
.incbin "CAT_GAMES\TEST.nes",$4010,$2000
Game0001_c_e:
.segment "ROM1"
Game0071:
.incbin "CAT_GAMES\1_GAMES\F-22.nes",$10,$20000
Game0071_e:
Game0213:
.incbin "CAT_GAMES\1_GAMES\Vanguard.nes",$10,$20000
Game0213_e:
Game0214:
.incbin "CAT_GAMES\1_GAMES\Vigilant.nes",$10,$8000
Game0214_e:
Game0215:
.incbin "CAT_GAMES\1_GAMES\Violent.nes",$10,$8000
Game0215_e:
Game0216:
.incbin "CAT_GAMES\1_GAMES\Volleyball.nes",$10,$8000
Game0216_e:
Game0217:
.incbin "CAT_GAMES\1_GAMES\War Zone.nes",$10,$8000
Game0217_e:
Game0219:
.incbin "CAT_GAMES\1_GAMES\Water Pipes.nes",$10,$8000
Game0219_e:
Game0220:
.incbin "CAT_GAMES\1_GAMES\Wild Worm.nes",$10,$8000
Game0220_e:
Game0221:
.incbin "CAT_GAMES\1_GAMES\Wonder Ball.nes",$10,$8000
Game0221_e:
Game0001:
.incbin "CAT_GAMES\TEST.nes",$10,$4000
Game0001_e:
.segment "ROM2"
Game0071_c:
.incbin "CAT_GAMES\1_GAMES\F-22.nes",$20010,$20000
Game0071_c_e:
Game0010_c:
.incbin "CAT_GAMES\1_GAMES\Airial Hero.nes",$8010,$8000
Game0010_c_e:
Game0213_c:
.incbin "CAT_GAMES\1_GAMES\Vanguard.nes",$20010,$8000
Game0213_c_e:
Game0013_c:
.incbin "CAT_GAMES\1_GAMES\Animal Blockes.nes",$8010,$4000
Game0013_c_e:
Game0033_c:
.incbin "CAT_GAMES\1_GAMES\Brother Ball.nes",$8010,$4000
Game0033_c_e:
Game0055_c:
.incbin "CAT_GAMES\1_GAMES\Danger Bridge.nes",$8010,$4000
Game0055_c_e:
Game0056_c:
.incbin "CAT_GAMES\1_GAMES\Dark Castle.nes",$4010,$4000
Game0056_c_e:
Game0067_c:
.incbin "CAT_GAMES\1_GAMES\Edacity Snakes.nes",$4010,$4000
Game0067_c_e:
Game0085_c:
.incbin "CAT_GAMES\1_GAMES\Frantic Fishing.nes",$8010,$4000
Game0085_c_e:
Game0122_c:
.incbin "CAT_GAMES\1_GAMES\Lawn Purge.nes",$8010,$4000
Game0122_c_e:
Game0166_c:
.incbin "CAT_GAMES\1_GAMES\Road Worker.nes",$8010,$4000
Game0166_c_e:
Game0216_c:
.incbin "CAT_GAMES\1_GAMES\Volleyball.nes",$8010,$4000
Game0216_c_e:
Game0200_c:
.incbin "CAT_GAMES\1_GAMES\The Farmer.nes",$4010,$2000
Game0200_c_e:
Game0201_c:
.incbin "CAT_GAMES\1_GAMES\Toad in the Hole.nes",$8010,$2000
Game0201_c_e:
Game0202_c:
.incbin "CAT_GAMES\1_GAMES\Toy Bricks.nes",$8010,$2000
Game0202_c_e:
Game0203_c:
.incbin "CAT_GAMES\1_GAMES\Toy Factory.nes",$8010,$2000
Game0203_c_e:
Game0204_c:
.incbin "CAT_GAMES\1_GAMES\Transmission.nes",$4010,$2000
Game0204_c_e:
Game0205_c:
.incbin "CAT_GAMES\1_GAMES\Triple Jump.nes",$4010,$2000
Game0205_c_e:
Game0206_c:
.incbin "CAT_GAMES\1_GAMES\Tunny.nes",$8010,$2000
Game0206_c_e:
Game0207_c:
.incbin "CAT_GAMES\1_GAMES\Turtles.nes",$4010,$2000
Game0207_c_e:
Game0208_c:
.incbin "CAT_GAMES\1_GAMES\Twin Cards.nes",$4010,$2000
Game0208_c_e:
Game0209_c:
.incbin "CAT_GAMES\1_GAMES\Twin Fish.nes",$4010,$2000
Game0209_c_e:
Game0210_c:
.incbin "CAT_GAMES\1_GAMES\UFO Race.nes",$4010,$2000
Game0210_c_e:
Game0211_c:
.incbin "CAT_GAMES\1_GAMES\Undersea Arena.nes",$4010,$2000
Game0211_c_e:
Game0212_c:
.incbin "CAT_GAMES\1_GAMES\UU Weapon.nes",$8010,$2000
Game0212_c_e:
Game0214_c:
.incbin "CAT_GAMES\1_GAMES\Vigilant.nes",$8010,$2000
Game0214_c_e:
Game0215_c:
.incbin "CAT_GAMES\1_GAMES\Violent.nes",$8010,$2000
Game0215_c_e:
Game0217_c:
.incbin "CAT_GAMES\1_GAMES\War Zone.nes",$8010,$2000
Game0217_c_e:
Game0218_c:
.incbin "CAT_GAMES\1_GAMES\Warrior.nes",$4010,$2000
Game0218_c_e:
Game0219_c:
.incbin "CAT_GAMES\1_GAMES\Water Pipes.nes",$8010,$2000
Game0219_c_e:
Game0220_c:
.incbin "CAT_GAMES\1_GAMES\Wild Worm.nes",$8010,$2000
Game0220_c_e:
Game0221_c:
.incbin "CAT_GAMES\1_GAMES\Wonder Ball.nes",$8010,$2000
Game0221_c_e:
Game0222_c:
.incbin "CAT_GAMES\1_GAMES\X Racing.nes",$4010,$2000
Game0222_c_e:
Game0223_c:
.incbin "CAT_GAMES\1_GAMES\Zero Gravity.nes",$4010,$2000
Game0223_c_e:
.segment "ROM3"
Game0173:
.incbin "CAT_GAMES\1_GAMES\Shift.nes",$10,$8000
Game0173_e:
Game0179:
.incbin "CAT_GAMES\1_GAMES\Smackdown.nes",$10,$8000
Game0179_e:
Game0181:
.incbin "CAT_GAMES\1_GAMES\Snowball.nes",$10,$8000
Game0181_e:
Game0182:
.incbin "CAT_GAMES\1_GAMES\Space Base.nes",$10,$8000
Game0182_e:
Game0184:
.incbin "CAT_GAMES\1_GAMES\Spades.nes",$10,$8000
Game0184_e:
Game0186:
.incbin "CAT_GAMES\1_GAMES\Spring World.nes",$10,$8000
Game0186_e:
Game0187:
.incbin "CAT_GAMES\1_GAMES\Sqoon.nes",$10,$8000
Game0187_e:
Game0189:
.incbin "CAT_GAMES\1_GAMES\Star.nes",$10,$8000
Game0189_e:
Game0192:
.incbin "CAT_GAMES\1_GAMES\Strong Pill.nes",$10,$8000
Game0192_e:
Game0193:
.incbin "CAT_GAMES\1_GAMES\Submarine.nes",$10,$8000
Game0193_e:
Game0194:
.incbin "CAT_GAMES\1_GAMES\Sudoku.nes",$10,$8000
Game0194_e:
Game0201:
.incbin "CAT_GAMES\1_GAMES\Toad in the Hole.nes",$10,$8000
Game0201_e:
Game0202:
.incbin "CAT_GAMES\1_GAMES\Toy Bricks.nes",$10,$8000
Game0202_e:
Game0203:
.incbin "CAT_GAMES\1_GAMES\Toy Factory.nes",$10,$8000
Game0203_e:
Game0206:
.incbin "CAT_GAMES\1_GAMES\Tunny.nes",$10,$8000
Game0206_e:
Game0212:
.incbin "CAT_GAMES\1_GAMES\UU Weapon.nes",$10,$8000
Game0212_e:
.segment "ROM4"
Game0135_c:
.incbin "CAT_GAMES\1_GAMES\Masked Man 2.nes",$8010,$2000
Game0135_c_e:
Game0136_c:
.incbin "CAT_GAMES\1_GAMES\Masked Man 3.nes",$8010,$2000
Game0136_c_e:
Game0137_c:
.incbin "CAT_GAMES\1_GAMES\Meccano.nes",$8010,$2000
Game0137_c_e:
Game0138_c:
.incbin "CAT_GAMES\1_GAMES\Memory Test.nes",$4010,$2000
Game0138_c_e:
Game0139_c:
.incbin "CAT_GAMES\1_GAMES\Mirror Devil World.nes",$8010,$2000
Game0139_c_e:
Game0140_c:
.incbin "CAT_GAMES\1_GAMES\Motoboat.nes",$4010,$2000
Game0140_c_e:
Game0141_c:
.incbin "CAT_GAMES\1_GAMES\Mouse Hero.nes",$8010,$2000
Game0141_c_e:
Game0142_c:
.incbin "CAT_GAMES\1_GAMES\Mouse Snare.nes",$8010,$2000
Game0142_c_e:
Game0143_c:
.incbin "CAT_GAMES\1_GAMES\Move Box.nes",$4010,$2000
Game0143_c_e:
Game0144_c:
.incbin "CAT_GAMES\1_GAMES\Mowing.nes",$8010,$2000
Game0144_c_e:
Game0145_c:
.incbin "CAT_GAMES\1_GAMES\Music Moment.nes",$8010,$2000
Game0145_c_e:
Game0146_c:
.incbin "CAT_GAMES\1_GAMES\NUT CRACKY.nes",$8010,$2000
Game0146_c_e:
Game0147_c:
.incbin "CAT_GAMES\1_GAMES\Octopus.nes",$8010,$2000
Game0147_c_e:
Game0148_c:
.incbin "CAT_GAMES\1_GAMES\Panzer Attack.nes",$4010,$2000
Game0148_c_e:
Game0149_c:
.incbin "CAT_GAMES\1_GAMES\Panzer Fly Car.nes",$8010,$2000
Game0149_c_e:
Game0150_c:
.incbin "CAT_GAMES\1_GAMES\Patternmaker.nes",$4010,$2000
Game0150_c_e:
Game0151_c:
.incbin "CAT_GAMES\1_GAMES\Penguin.nes",$4010,$2000
Game0151_c_e:
Game0152_c:
.incbin "CAT_GAMES\1_GAMES\Pizza Boy.nes",$8010,$2000
Game0152_c_e:
Game0153_c:
.incbin "CAT_GAMES\1_GAMES\Pobble.nes",$4010,$2000
Game0153_c_e:
Game0154_c:
.incbin "CAT_GAMES\1_GAMES\Polar Bat.nes",$4010,$2000
Game0154_c_e:
Game0155_c:
.incbin "CAT_GAMES\1_GAMES\Police Dog Lasy.nes",$8010,$2000
Game0155_c_e:
Game0156_c:
.incbin "CAT_GAMES\1_GAMES\Polk.nes",$8010,$2000
Game0156_c_e:
Game0157_c:
.incbin "CAT_GAMES\1_GAMES\PongPong.nes",$8010,$2000
Game0157_c_e:
Game0158_c:
.incbin "CAT_GAMES\1_GAMES\Pulveration.nes",$8010,$2000
Game0158_c_e:
Game0159_c:
.incbin "CAT_GAMES\1_GAMES\Puzzle.nes",$4010,$2000
Game0159_c_e:
Game0160_c:
.incbin "CAT_GAMES\1_GAMES\Rabbit Village.nes",$8010,$2000
Game0160_c_e:
Game0161_c:
.incbin "CAT_GAMES\1_GAMES\Radish Field.nes",$4010,$2000
Game0161_c_e:
Game0162_c:
.incbin "CAT_GAMES\1_GAMES\Rescue Kuck.nes",$4010,$2000
Game0162_c_e:
Game0163_c:
.incbin "CAT_GAMES\1_GAMES\Resistant.nes",$4010,$2000
Game0163_c_e:
Game0164_c:
.incbin "CAT_GAMES\1_GAMES\Risker.nes",$4010,$2000
Game0164_c_e:
Game0165_c:
.incbin "CAT_GAMES\1_GAMES\River Jump.nes",$8010,$2000
Game0165_c_e:
Game0167_c:
.incbin "CAT_GAMES\1_GAMES\Robot.nes",$4010,$2000
Game0167_c_e:
Game0168_c:
.incbin "CAT_GAMES\1_GAMES\Rural Goblin.nes",$4010,$2000
Game0168_c_e:
Game0169_c:
.incbin "CAT_GAMES\1_GAMES\Sea Wolf.nes",$8010,$2000
Game0169_c_e:
Game0170_c:
.incbin "CAT_GAMES\1_GAMES\Sea-Maid.nes",$8010,$2000
Game0170_c_e:
Game0171_c:
.incbin "CAT_GAMES\1_GAMES\Seaport Guarl.nes",$8010,$2000
Game0171_c_e:
Game0172_c:
.incbin "CAT_GAMES\1_GAMES\Season Garden.nes",$4010,$2000
Game0172_c_e:
Game0173_c:
.incbin "CAT_GAMES\1_GAMES\Shift.nes",$8010,$2000
Game0173_c_e:
Game0174_c:
.incbin "CAT_GAMES\1_GAMES\Shooting.nes",$4010,$2000
Game0174_c_e:
Game0175_c:
.incbin "CAT_GAMES\1_GAMES\Shot Put.nes",$4010,$2000
Game0175_c_e:
Game0176_c:
.incbin "CAT_GAMES\1_GAMES\Shrew Mouse.nes",$4010,$2000
Game0176_c_e:
Game0177_c:
.incbin "CAT_GAMES\1_GAMES\Silent Hunter.nes",$4010,$2000
Game0177_c_e:
Game0178_c:
.incbin "CAT_GAMES\1_GAMES\Sky Invader.nes",$4010,$2000
Game0178_c_e:
Game0179_c:
.incbin "CAT_GAMES\1_GAMES\Smackdown.nes",$8010,$2000
Game0179_c_e:
Game0180_c:
.incbin "CAT_GAMES\1_GAMES\Small Dinosaur.nes",$4010,$2000
Game0180_c_e:
Game0181_c:
.incbin "CAT_GAMES\1_GAMES\Snowball.nes",$8010,$2000
Game0181_c_e:
Game0182_c:
.incbin "CAT_GAMES\1_GAMES\Space Base.nes",$8010,$2000
Game0182_c_e:
Game0183_c:
.incbin "CAT_GAMES\1_GAMES\Space War.nes",$4010,$2000
Game0183_c_e:
Game0184_c:
.incbin "CAT_GAMES\1_GAMES\Spades.nes",$8010,$2000
Game0184_c_e:
Game0185_c:
.incbin "CAT_GAMES\1_GAMES\Spar.nes",$4010,$2000
Game0185_c_e:
Game0186_c:
.incbin "CAT_GAMES\1_GAMES\Spring World.nes",$8010,$2000
Game0186_c_e:
Game0187_c:
.incbin "CAT_GAMES\1_GAMES\Sqoon.nes",$8010,$2000
Game0187_c_e:
Game0188_c:
.incbin "CAT_GAMES\1_GAMES\Star Fighter.nes",$4010,$2000
Game0188_c_e:
Game0189_c:
.incbin "CAT_GAMES\1_GAMES\Star.nes",$8010,$2000
Game0189_c_e:
Game0190_c:
.incbin "CAT_GAMES\1_GAMES\Star_2.nes",$4010,$2000
Game0190_c_e:
Game0191_c:
.incbin "CAT_GAMES\1_GAMES\Strafe.nes",$4010,$2000
Game0191_c_e:
Game0192_c:
.incbin "CAT_GAMES\1_GAMES\Strong Pill.nes",$8010,$2000
Game0192_c_e:
Game0193_c:
.incbin "CAT_GAMES\1_GAMES\Submarine.nes",$8010,$2000
Game0193_c_e:
Game0194_c:
.incbin "CAT_GAMES\1_GAMES\Sudoku.nes",$8010,$2000
Game0194_c_e:
Game0195_c:
.incbin "CAT_GAMES\1_GAMES\Surface Fire.nes",$4010,$2000
Game0195_c_e:
Game0196_c:
.incbin "CAT_GAMES\1_GAMES\Surfg Sport.nes",$4010,$2000
Game0196_c_e:
Game0197_c:
.incbin "CAT_GAMES\1_GAMES\Tactful.nes",$4010,$2000
Game0197_c_e:
Game0198_c:
.incbin "CAT_GAMES\1_GAMES\Tennis.nes",$4010,$2000
Game0198_c_e:
Game0199_c:
.incbin "CAT_GAMES\1_GAMES\The Archer.nes",$4010,$2000
Game0199_c_e:
.segment "ROM5"
Game0144:
.incbin "CAT_GAMES\1_GAMES\Mowing.nes",$10,$8000
Game0144_e:
Game0145:
.incbin "CAT_GAMES\1_GAMES\Music Moment.nes",$10,$8000
Game0145_e:
Game0146:
.incbin "CAT_GAMES\1_GAMES\NUT CRACKY.nes",$10,$8000
Game0146_e:
Game0147:
.incbin "CAT_GAMES\1_GAMES\Octopus.nes",$10,$8000
Game0147_e:
Game0149:
.incbin "CAT_GAMES\1_GAMES\Panzer Fly Car.nes",$10,$8000
Game0149_e:
Game0152:
.incbin "CAT_GAMES\1_GAMES\Pizza Boy.nes",$10,$8000
Game0152_e:
Game0155:
.incbin "CAT_GAMES\1_GAMES\Police Dog Lasy.nes",$10,$8000
Game0155_e:
Game0156:
.incbin "CAT_GAMES\1_GAMES\Polk.nes",$10,$8000
Game0156_e:
Game0157:
.incbin "CAT_GAMES\1_GAMES\PongPong.nes",$10,$8000
Game0157_e:
Game0158:
.incbin "CAT_GAMES\1_GAMES\Pulveration.nes",$10,$8000
Game0158_e:
Game0160:
.incbin "CAT_GAMES\1_GAMES\Rabbit Village.nes",$10,$8000
Game0160_e:
Game0165:
.incbin "CAT_GAMES\1_GAMES\River Jump.nes",$10,$8000
Game0165_e:
Game0166:
.incbin "CAT_GAMES\1_GAMES\Road Worker.nes",$10,$8000
Game0166_e:
Game0169:
.incbin "CAT_GAMES\1_GAMES\Sea Wolf.nes",$10,$8000
Game0169_e:
Game0170:
.incbin "CAT_GAMES\1_GAMES\Sea-Maid.nes",$10,$8000
Game0170_e:
Game0171:
.incbin "CAT_GAMES\1_GAMES\Seaport Guarl.nes",$10,$8000
Game0171_e:
.segment "ROM6"
Game0068_c:
.incbin "CAT_GAMES\1_GAMES\Egg Contest.nes",$8010,$2000
Game0068_c_e:
Game0069_c:
.incbin "CAT_GAMES\1_GAMES\Eidolon's Revenge.nes",$8010,$2000
Game0069_c_e:
Game0070_c:
.incbin "CAT_GAMES\1_GAMES\Escapeway.nes",$8010,$2000
Game0070_c_e:
Game0072_c:
.incbin "CAT_GAMES\1_GAMES\Fairy's Treasure.nes",$8010,$2000
Game0072_c_e:
Game0073_c:
.incbin "CAT_GAMES\1_GAMES\Falling Blocks.nes",$8010,$2000
Game0073_c_e:
Game0074_c:
.incbin "CAT_GAMES\1_GAMES\Falling.nes",$4010,$2000
Game0074_c_e:
Game0075_c:
.incbin "CAT_GAMES\1_GAMES\Fated Pirate.nes",$8010,$2000
Game0075_c_e:
Game0076_c:
.incbin "CAT_GAMES\1_GAMES\Final Blood.nes",$8010,$2000
Game0076_c_e:
Game0077_c:
.incbin "CAT_GAMES\1_GAMES\Fire Dragon.nes",$8010,$2000
Game0077_c_e:
Game0078_c:
.incbin "CAT_GAMES\1_GAMES\Firebase.nes",$4010,$2000
Game0078_c_e:
Game0079_c:
.incbin "CAT_GAMES\1_GAMES\First Defender.nes",$4010,$2000
Game0079_c_e:
Game0080_c:
.incbin "CAT_GAMES\1_GAMES\Fish Story.nes",$8010,$2000
Game0080_c_e:
Game0081_c:
.incbin "CAT_GAMES\1_GAMES\Fish War.nes",$4010,$2000
Game0081_c_e:
Game0082_c:
.incbin "CAT_GAMES\1_GAMES\Fisher.nes",$4010,$2000
Game0082_c_e:
Game0083_c:
.incbin "CAT_GAMES\1_GAMES\Five Days.nes",$4010,$2000
Game0083_c_e:
Game0084_c:
.incbin "CAT_GAMES\1_GAMES\Fling Ball.nes",$8010,$2000
Game0084_c_e:
Game0086_c:
.incbin "CAT_GAMES\1_GAMES\Frantic Mouse.nes",$4010,$2000
Game0086_c_e:
Game0087_c:
.incbin "CAT_GAMES\1_GAMES\Freecell.nes",$4010,$2000
Game0087_c_e:
Game0088_c:
.incbin "CAT_GAMES\1_GAMES\Fruit Dish.nes",$4010,$2000
Game0088_c_e:
Game0089_c:
.incbin "CAT_GAMES\1_GAMES\Fruit Gift.nes",$4010,$2000
Game0089_c_e:
Game0090_c:
.incbin "CAT_GAMES\1_GAMES\Fruit Pig.nes",$8010,$2000
Game0090_c_e:
Game0091_c:
.incbin "CAT_GAMES\1_GAMES\Future Tank.nes",$4010,$2000
Game0091_c_e:
Game0092_c:
.incbin "CAT_GAMES\1_GAMES\Gallagant.nes",$4010,$2000
Game0092_c_e:
Game0093_c:
.incbin "CAT_GAMES\1_GAMES\Garden War.nes",$4010,$2000
Game0093_c_e:
Game0094_c:
.incbin "CAT_GAMES\1_GAMES\Ghost Castle.nes",$8010,$2000
Game0094_c_e:
Game0095_c:
.incbin "CAT_GAMES\1_GAMES\Goblet Tower.nes",$4010,$2000
Game0095_c_e:
Game0096_c:
.incbin "CAT_GAMES\1_GAMES\Golden Bird.nes",$8010,$2000
Game0096_c_e:
Game0097_c:
.incbin "CAT_GAMES\1_GAMES\Goodhand.nes",$4010,$2000
Game0097_c_e:
Game0098_c:
.incbin "CAT_GAMES\1_GAMES\Gradirs.nes",$8010,$2000
Game0098_c_e:
Game0099_c:
.incbin "CAT_GAMES\1_GAMES\Greedy.nes",$8010,$2000
Game0099_c_e:
Game0100_c:
.incbin "CAT_GAMES\1_GAMES\Grot Kid.nes",$4010,$2000
Game0100_c_e:
Game0101_c:
.incbin "CAT_GAMES\1_GAMES\Hallihoo.nes",$4010,$2000
Game0101_c_e:
Game0102_c:
.incbin "CAT_GAMES\1_GAMES\Hammer and Nail.nes",$8010,$2000
Game0102_c_e:
Game0103_c:
.incbin "CAT_GAMES\1_GAMES\Happy Adventure.nes",$4010,$2000
Game0103_c_e:
Game0104_c:
.incbin "CAT_GAMES\1_GAMES\Happy Match.nes",$8010,$2000
Game0104_c_e:
Game0105_c:
.incbin "CAT_GAMES\1_GAMES\Hassle.nes",$4010,$2000
Game0105_c_e:
Game0106_c:
.incbin "CAT_GAMES\1_GAMES\Hexapod War.nes",$4010,$2000
Game0106_c_e:
Game0107_c:
.incbin "CAT_GAMES\1_GAMES\High Jump.nes",$4010,$2000
Game0107_c_e:
Game0108_c:
.incbin "CAT_GAMES\1_GAMES\Highcard.nes",$8010,$2000
Game0108_c_e:
Game0109_c:
.incbin "CAT_GAMES\1_GAMES\Hit-Mouse.nes",$4010,$2000
Game0109_c_e:
Game0110_c:
.incbin "CAT_GAMES\1_GAMES\Hoodle.nes",$4010,$2000
Game0110_c_e:
Game0111_c:
.incbin "CAT_GAMES\1_GAMES\Hot Speed.nes",$4010,$2000
Game0111_c_e:
Game0112_c:
.incbin "CAT_GAMES\1_GAMES\Hurry Burry.nes",$8010,$2000
Game0112_c_e:
Game0113_c:
.incbin "CAT_GAMES\1_GAMES\Ice Ocean.nes",$8010,$2000
Game0113_c_e:
Game0114_c:
.incbin "CAT_GAMES\1_GAMES\IQ Champion.nes",$8010,$2000
Game0114_c_e:
Game0115_c:
.incbin "CAT_GAMES\1_GAMES\Island.nes",$8010,$2000
Game0115_c_e:
Game0116_c:
.incbin "CAT_GAMES\1_GAMES\Javelin Throw.nes",$4010,$2000
Game0116_c_e:
Game0117_c:
.incbin "CAT_GAMES\1_GAMES\Jump-Jump.nes",$8010,$2000
Game0117_c_e:
Game0118_c:
.incbin "CAT_GAMES\1_GAMES\Jumping Kid.nes",$8010,$2000
Game0118_c_e:
Game0119_c:
.incbin "CAT_GAMES\1_GAMES\Jungly Guy.nes",$4010,$2000
Game0119_c_e:
Game0120_c:
.incbin "CAT_GAMES\1_GAMES\Labyrinth.nes",$4010,$2000
Game0120_c_e:
Game0121_c:
.incbin "CAT_GAMES\1_GAMES\Lattice Winner.nes",$8010,$2000
Game0121_c_e:
Game0123_c:
.incbin "CAT_GAMES\1_GAMES\Levin Action.nes",$4010,$2000
Game0123_c_e:
Game0124_c:
.incbin "CAT_GAMES\1_GAMES\Lightning.nes",$8010,$2000
Game0124_c_e:
Game0125_c:
.incbin "CAT_GAMES\1_GAMES\Little-Witch.nes",$8010,$2000
Game0125_c_e:
Game0126_c:
.incbin "CAT_GAMES\1_GAMES\Long Jump.nes",$4010,$2000
Game0126_c_e:
Game0127_c:
.incbin "CAT_GAMES\1_GAMES\Lunarian.nes",$4010,$2000
Game0127_c_e:
Game0128_c:
.incbin "CAT_GAMES\1_GAMES\Lunation.nes",$4010,$2000
Game0128_c_e:
Game0129_c:
.incbin "CAT_GAMES\1_GAMES\Mad Xmas.nes",$4010,$2000
Game0129_c_e:
Game0130_c:
.incbin "CAT_GAMES\1_GAMES\Magic Bubble.nes",$4010,$2000
Game0130_c_e:
Game0131_c:
.incbin "CAT_GAMES\1_GAMES\Magic Egg.nes",$8010,$2000
Game0131_c_e:
Game0132_c:
.incbin "CAT_GAMES\1_GAMES\Man in Red.nes",$4010,$2000
Game0132_c_e:
Game0133_c:
.incbin "CAT_GAMES\1_GAMES\Mars.nes",$4010,$2000
Game0133_c_e:
Game0134_c:
.incbin "CAT_GAMES\1_GAMES\Masked Man 1.nes",$8010,$2000
Game0134_c_e:
.segment "ROM7"
Game0114:
.incbin "CAT_GAMES\1_GAMES\IQ Champion.nes",$10,$8000
Game0114_e:
Game0115:
.incbin "CAT_GAMES\1_GAMES\Island.nes",$10,$8000
Game0115_e:
Game0117:
.incbin "CAT_GAMES\1_GAMES\Jump-Jump.nes",$10,$8000
Game0117_e:
Game0118:
.incbin "CAT_GAMES\1_GAMES\Jumping Kid.nes",$10,$8000
Game0118_e:
Game0121:
.incbin "CAT_GAMES\1_GAMES\Lattice Winner.nes",$10,$8000
Game0121_e:
Game0122:
.incbin "CAT_GAMES\1_GAMES\Lawn Purge.nes",$10,$8000
Game0122_e:
Game0124:
.incbin "CAT_GAMES\1_GAMES\Lightning.nes",$10,$8000
Game0124_e:
Game0125:
.incbin "CAT_GAMES\1_GAMES\Little-Witch.nes",$10,$8000
Game0125_e:
Game0131:
.incbin "CAT_GAMES\1_GAMES\Magic Egg.nes",$10,$8000
Game0131_e:
Game0134:
.incbin "CAT_GAMES\1_GAMES\Masked Man 1.nes",$10,$8000
Game0134_e:
Game0135:
.incbin "CAT_GAMES\1_GAMES\Masked Man 2.nes",$10,$8000
Game0135_e:
Game0136:
.incbin "CAT_GAMES\1_GAMES\Masked Man 3.nes",$10,$8000
Game0136_e:
Game0137:
.incbin "CAT_GAMES\1_GAMES\Meccano.nes",$10,$8000
Game0137_e:
Game0139:
.incbin "CAT_GAMES\1_GAMES\Mirror Devil World.nes",$10,$8000
Game0139_e:
Game0141:
.incbin "CAT_GAMES\1_GAMES\Mouse Hero.nes",$10,$8000
Game0141_e:
Game0142:
.incbin "CAT_GAMES\1_GAMES\Mouse Snare.nes",$10,$8000
Game0142_e:
.segment "ROM8"
Game0002_c:
.incbin "CAT_GAMES\1_GAMES\100m Dash.nes",$4010,$2000
Game0002_c_e:
Game0003_c:
.incbin "CAT_GAMES\1_GAMES\110m Hurdles.nes",$4010,$2000
Game0003_c_e:
Game0004_c:
.incbin "CAT_GAMES\1_GAMES\Abscondee.nes",$8010,$2000
Game0004_c_e:
Game0005_c:
.incbin "CAT_GAMES\1_GAMES\Aether Cruiser.nes",$8010,$2000
Game0005_c_e:
Game0006_c:
.incbin "CAT_GAMES\1_GAMES\Aether.nes",$4010,$2000
Game0006_c_e:
Game0007_c:
.incbin "CAT_GAMES\1_GAMES\Aim Cruise.nes",$8010,$2000
Game0007_c_e:
Game0008_c:
.incbin "CAT_GAMES\1_GAMES\Aimless.nes",$4010,$2000
Game0008_c_e:
Game0009_c:
.incbin "CAT_GAMES\1_GAMES\Air Alert.nes",$8010,$2000
Game0009_c_e:
Game0011_c:
.incbin "CAT_GAMES\1_GAMES\Airway.nes",$8010,$2000
Game0011_c_e:
Game0012_c:
.incbin "CAT_GAMES\1_GAMES\Angel.nes",$4010,$2000
Game0012_c_e:
Game0014_c:
.incbin "CAT_GAMES\1_GAMES\Animal Contest.nes",$8010,$2000
Game0014_c_e:
Game0015_c:
.incbin "CAT_GAMES\1_GAMES\Antiquarium.nes",$4010,$2000
Game0015_c_e:
Game0016_c:
.incbin "CAT_GAMES\1_GAMES\Apple Chess.nes",$4010,$2000
Game0016_c_e:
Game0017_c:
.incbin "CAT_GAMES\1_GAMES\Archery.nes",$4010,$2000
Game0017_c_e:
Game0018_c:
.incbin "CAT_GAMES\1_GAMES\Arena.nes",$4010,$2000
Game0018_c_e:
Game0019_c:
.incbin "CAT_GAMES\1_GAMES\Assart.nes",$4010,$2000
Game0019_c_e:
Game0020_c:
.incbin "CAT_GAMES\1_GAMES\Awful Rushing.nes",$4010,$2000
Game0020_c_e:
Game0021_c:
.incbin "CAT_GAMES\1_GAMES\Balloon Shoot.nes",$8010,$2000
Game0021_c_e:
Game0022_c:
.incbin "CAT_GAMES\1_GAMES\Bandits.nes",$4010,$2000
Game0022_c_e:
Game0023_c:
.incbin "CAT_GAMES\1_GAMES\Baseball.nes",$4010,$2000
Game0023_c_e:
Game0024_c:
.incbin "CAT_GAMES\1_GAMES\Battle.nes",$8010,$2000
Game0024_c_e:
Game0025_c:
.incbin "CAT_GAMES\1_GAMES\Bicycle Race.nes",$8010,$2000
Game0025_c_e:
Game0026_c:
.incbin "CAT_GAMES\1_GAMES\Billiards.nes",$4010,$2000
Game0026_c_e:
Game0027_c:
.incbin "CAT_GAMES\1_GAMES\Bitha.nes",$4010,$2000
Game0027_c_e:
Game0028_c:
.incbin "CAT_GAMES\1_GAMES\Blob Buster.nes",$8010,$2000
Game0028_c_e:
Game0029_c:
.incbin "CAT_GAMES\1_GAMES\Boat Race 1.nes",$4010,$2000
Game0029_c_e:
Game0030_c:
.incbin "CAT_GAMES\1_GAMES\Boat Race 2.nes",$8010,$2000
Game0030_c_e:
Game0031_c:
.incbin "CAT_GAMES\1_GAMES\Bomb King.nes",$4010,$2000
Game0031_c_e:
Game0032_c:
.incbin "CAT_GAMES\1_GAMES\Bounce.nes",$4010,$2000
Game0032_c_e:
Game0034_c:
.incbin "CAT_GAMES\1_GAMES\Bubble.nes",$4010,$2000
Game0034_c_e:
Game0035_c:
.incbin "CAT_GAMES\1_GAMES\Bug Catcher.nes",$8010,$2000
Game0035_c_e:
Game0036_c:
.incbin "CAT_GAMES\1_GAMES\Bug.nes",$8010,$2000
Game0036_c_e:
Game0037_c:
.incbin "CAT_GAMES\1_GAMES\BugBear.nes",$4010,$2000
Game0037_c_e:
Game0038_c:
.incbin "CAT_GAMES\1_GAMES\Build Pillars.nes",$4010,$2000
Game0038_c_e:
Game0039_c:
.incbin "CAT_GAMES\1_GAMES\Burrow.nes",$4010,$2000
Game0039_c_e:
Game0040_c:
.incbin "CAT_GAMES\1_GAMES\Busy Bar.nes",$8010,$2000
Game0040_c_e:
Game0041_c:
.incbin "CAT_GAMES\1_GAMES\Candy Workshop.nes",$8010,$2000
Game0041_c_e:
Game0042_c:
.incbin "CAT_GAMES\1_GAMES\Cannonade.nes",$4010,$2000
Game0042_c_e:
Game0043_c:
.incbin "CAT_GAMES\1_GAMES\Care Bear.nes",$4010,$2000
Game0043_c_e:
Game0044_c:
.incbin "CAT_GAMES\1_GAMES\Checkers.nes",$8010,$2000
Game0044_c_e:
Game0045_c:
.incbin "CAT_GAMES\1_GAMES\Close Quarters.nes",$4010,$2000
Game0045_c_e:
Game0046_c:
.incbin "CAT_GAMES\1_GAMES\Coast Guard.nes",$4010,$2000
Game0046_c_e:
Game0047_c:
.incbin "CAT_GAMES\1_GAMES\Cobra of Sky.nes",$4010,$2000
Game0047_c_e:
Game0048_c:
.incbin "CAT_GAMES\1_GAMES\Combata.nes",$4010,$2000
Game0048_c_e:
Game0049_c:
.incbin "CAT_GAMES\1_GAMES\Conqueror.nes",$4010,$2000
Game0049_c_e:
Game0050_c:
.incbin "CAT_GAMES\1_GAMES\Contest 2004.nes",$8010,$2000
Game0050_c_e:
Game0051_c:
.incbin "CAT_GAMES\1_GAMES\Crystal Ball.nes",$8010,$2000
Game0051_c_e:
Game0052_c:
.incbin "CAT_GAMES\1_GAMES\Crystal Blast.nes",$8010,$2000
Game0052_c_e:
Game0053_c:
.incbin "CAT_GAMES\1_GAMES\Cub Adventure.nes",$4010,$2000
Game0053_c_e:
Game0054_c:
.incbin "CAT_GAMES\1_GAMES\Dada.nes",$4010,$2000
Game0054_c_e:
Game0057_c:
.incbin "CAT_GAMES\1_GAMES\Defensive.nes",$4010,$2000
Game0057_c_e:
Game0058_c:
.incbin "CAT_GAMES\1_GAMES\Deformable.nes",$8010,$2000
Game0058_c_e:
Game0059_c:
.incbin "CAT_GAMES\1_GAMES\Dejectile.nes",$8010,$2000
Game0059_c_e:
Game0060_c:
.incbin "CAT_GAMES\1_GAMES\Depth Bomb.nes",$4010,$2000
Game0060_c_e:
Game0061_c:
.incbin "CAT_GAMES\1_GAMES\Devildom Doom.nes",$4010,$2000
Game0061_c_e:
Game0062_c:
.incbin "CAT_GAMES\1_GAMES\Dice.nes",$4010,$2000
Game0062_c_e:
Game0063_c:
.incbin "CAT_GAMES\1_GAMES\Discus Put.nes",$4010,$2000
Game0063_c_e:
Game0064_c:
.incbin "CAT_GAMES\1_GAMES\Dominoes.nes",$4010,$2000
Game0064_c_e:
Game0065_c:
.incbin "CAT_GAMES\1_GAMES\Dragon Den.nes",$4010,$2000
Game0065_c_e:
Game0066_c:
.incbin "CAT_GAMES\1_GAMES\Dune War.nes",$4010,$2000
Game0066_c_e:
.segment "ROM9"
Game0075:
.incbin "CAT_GAMES\1_GAMES\Fated Pirate.nes",$10,$8000
Game0075_e:
Game0076:
.incbin "CAT_GAMES\1_GAMES\Final Blood.nes",$10,$8000
Game0076_e:
Game0077:
.incbin "CAT_GAMES\1_GAMES\Fire Dragon.nes",$10,$8000
Game0077_e:
Game0080:
.incbin "CAT_GAMES\1_GAMES\Fish Story.nes",$10,$8000
Game0080_e:
Game0084:
.incbin "CAT_GAMES\1_GAMES\Fling Ball.nes",$10,$8000
Game0084_e:
Game0085:
.incbin "CAT_GAMES\1_GAMES\Frantic Fishing.nes",$10,$8000
Game0085_e:
Game0090:
.incbin "CAT_GAMES\1_GAMES\Fruit Pig.nes",$10,$8000
Game0090_e:
Game0094:
.incbin "CAT_GAMES\1_GAMES\Ghost Castle.nes",$10,$8000
Game0094_e:
Game0096:
.incbin "CAT_GAMES\1_GAMES\Golden Bird.nes",$10,$8000
Game0096_e:
Game0098:
.incbin "CAT_GAMES\1_GAMES\Gradirs.nes",$10,$8000
Game0098_e:
Game0099:
.incbin "CAT_GAMES\1_GAMES\Greedy.nes",$10,$8000
Game0099_e:
Game0102:
.incbin "CAT_GAMES\1_GAMES\Hammer and Nail.nes",$10,$8000
Game0102_e:
Game0104:
.incbin "CAT_GAMES\1_GAMES\Happy Match.nes",$10,$8000
Game0104_e:
Game0108:
.incbin "CAT_GAMES\1_GAMES\Highcard.nes",$10,$8000
Game0108_e:
Game0112:
.incbin "CAT_GAMES\1_GAMES\Hurry Burry.nes",$10,$8000
Game0112_e:
Game0113:
.incbin "CAT_GAMES\1_GAMES\Ice Ocean.nes",$10,$8000
Game0113_e:
.segment "ROM10"
Game0035:
.incbin "CAT_GAMES\1_GAMES\Bug Catcher.nes",$10,$8000
Game0035_e:
Game0036:
.incbin "CAT_GAMES\1_GAMES\Bug.nes",$10,$8000
Game0036_e:
Game0040:
.incbin "CAT_GAMES\1_GAMES\Busy Bar.nes",$10,$8000
Game0040_e:
Game0041:
.incbin "CAT_GAMES\1_GAMES\Candy Workshop.nes",$10,$8000
Game0041_e:
Game0044:
.incbin "CAT_GAMES\1_GAMES\Checkers.nes",$10,$8000
Game0044_e:
Game0050:
.incbin "CAT_GAMES\1_GAMES\Contest 2004.nes",$10,$8000
Game0050_e:
Game0051:
.incbin "CAT_GAMES\1_GAMES\Crystal Ball.nes",$10,$8000
Game0051_e:
Game0052:
.incbin "CAT_GAMES\1_GAMES\Crystal Blast.nes",$10,$8000
Game0052_e:
Game0055:
.incbin "CAT_GAMES\1_GAMES\Danger Bridge.nes",$10,$8000
Game0055_e:
Game0058:
.incbin "CAT_GAMES\1_GAMES\Deformable.nes",$10,$8000
Game0058_e:
Game0059:
.incbin "CAT_GAMES\1_GAMES\Dejectile.nes",$10,$8000
Game0059_e:
Game0068:
.incbin "CAT_GAMES\1_GAMES\Egg Contest.nes",$10,$8000
Game0068_e:
Game0069:
.incbin "CAT_GAMES\1_GAMES\Eidolon's Revenge.nes",$10,$8000
Game0069_e:
Game0070:
.incbin "CAT_GAMES\1_GAMES\Escapeway.nes",$10,$8000
Game0070_e:
Game0072:
.incbin "CAT_GAMES\1_GAMES\Fairy's Treasure.nes",$10,$8000
Game0072_e:
Game0073:
.incbin "CAT_GAMES\1_GAMES\Falling Blocks.nes",$10,$8000
Game0073_e:
.segment "ROM11"
Game0004:
.incbin "CAT_GAMES\1_GAMES\Abscondee.nes",$10,$8000
Game0004_e:
Game0005:
.incbin "CAT_GAMES\1_GAMES\Aether Cruiser.nes",$10,$8000
Game0005_e:
Game0007:
.incbin "CAT_GAMES\1_GAMES\Aim Cruise.nes",$10,$8000
Game0007_e:
Game0009:
.incbin "CAT_GAMES\1_GAMES\Air Alert.nes",$10,$8000
Game0009_e:
Game0010:
.incbin "CAT_GAMES\1_GAMES\Airial Hero.nes",$10,$8000
Game0010_e:
Game0011:
.incbin "CAT_GAMES\1_GAMES\Airway.nes",$10,$8000
Game0011_e:
Game0013:
.incbin "CAT_GAMES\1_GAMES\Animal Blockes.nes",$10,$8000
Game0013_e:
Game0014:
.incbin "CAT_GAMES\1_GAMES\Animal Contest.nes",$10,$8000
Game0014_e:
Game0021:
.incbin "CAT_GAMES\1_GAMES\Balloon Shoot.nes",$10,$8000
Game0021_e:
Game0024:
.incbin "CAT_GAMES\1_GAMES\Battle.nes",$10,$8000
Game0024_e:
Game0025:
.incbin "CAT_GAMES\1_GAMES\Bicycle Race.nes",$10,$8000
Game0025_e:
Game0028:
.incbin "CAT_GAMES\1_GAMES\Blob Buster.nes",$10,$8000
Game0028_e:
Game0030:
.incbin "CAT_GAMES\1_GAMES\Boat Race 2.nes",$10,$8000
Game0030_e:
Game0033:
.incbin "CAT_GAMES\1_GAMES\Brother Ball.nes",$10,$8000
Game0033_e:
Game0211:
.incbin "CAT_GAMES\1_GAMES\Undersea Arena.nes",$10,$4000
Game0211_e:
Game0218:
.incbin "CAT_GAMES\1_GAMES\Warrior.nes",$10,$4000
Game0218_e:
Game0222:
.incbin "CAT_GAMES\1_GAMES\X Racing.nes",$10,$4000
Game0222_e:
Game0223:
.incbin "CAT_GAMES\1_GAMES\Zero Gravity.nes",$10,$4000
Game0223_e:
.segment "ROM12"
Game0154:
.incbin "CAT_GAMES\1_GAMES\Polar Bat.nes",$10,$4000
Game0154_e:
Game0159:
.incbin "CAT_GAMES\1_GAMES\Puzzle.nes",$10,$4000
Game0159_e:
Game0161:
.incbin "CAT_GAMES\1_GAMES\Radish Field.nes",$10,$4000
Game0161_e:
Game0162:
.incbin "CAT_GAMES\1_GAMES\Rescue Kuck.nes",$10,$4000
Game0162_e:
Game0163:
.incbin "CAT_GAMES\1_GAMES\Resistant.nes",$10,$4000
Game0163_e:
Game0164:
.incbin "CAT_GAMES\1_GAMES\Risker.nes",$10,$4000
Game0164_e:
Game0167:
.incbin "CAT_GAMES\1_GAMES\Robot.nes",$10,$4000
Game0167_e:
Game0168:
.incbin "CAT_GAMES\1_GAMES\Rural Goblin.nes",$10,$4000
Game0168_e:
Game0172:
.incbin "CAT_GAMES\1_GAMES\Season Garden.nes",$10,$4000
Game0172_e:
Game0174:
.incbin "CAT_GAMES\1_GAMES\Shooting.nes",$10,$4000
Game0174_e:
Game0175:
.incbin "CAT_GAMES\1_GAMES\Shot Put.nes",$10,$4000
Game0175_e:
Game0176:
.incbin "CAT_GAMES\1_GAMES\Shrew Mouse.nes",$10,$4000
Game0176_e:
Game0177:
.incbin "CAT_GAMES\1_GAMES\Silent Hunter.nes",$10,$4000
Game0177_e:
Game0178:
.incbin "CAT_GAMES\1_GAMES\Sky Invader.nes",$10,$4000
Game0178_e:
Game0180:
.incbin "CAT_GAMES\1_GAMES\Small Dinosaur.nes",$10,$4000
Game0180_e:
Game0183:
.incbin "CAT_GAMES\1_GAMES\Space War.nes",$10,$4000
Game0183_e:
Game0185:
.incbin "CAT_GAMES\1_GAMES\Spar.nes",$10,$4000
Game0185_e:
Game0188:
.incbin "CAT_GAMES\1_GAMES\Star Fighter.nes",$10,$4000
Game0188_e:
Game0190:
.incbin "CAT_GAMES\1_GAMES\Star_2.nes",$10,$4000
Game0190_e:
Game0191:
.incbin "CAT_GAMES\1_GAMES\Strafe.nes",$10,$4000
Game0191_e:
Game0195:
.incbin "CAT_GAMES\1_GAMES\Surface Fire.nes",$10,$4000
Game0195_e:
Game0196:
.incbin "CAT_GAMES\1_GAMES\Surfg Sport.nes",$10,$4000
Game0196_e:
Game0197:
.incbin "CAT_GAMES\1_GAMES\Tactful.nes",$10,$4000
Game0197_e:
Game0198:
.incbin "CAT_GAMES\1_GAMES\Tennis.nes",$10,$4000
Game0198_e:
Game0199:
.incbin "CAT_GAMES\1_GAMES\The Archer.nes",$10,$4000
Game0199_e:
Game0200:
.incbin "CAT_GAMES\1_GAMES\The Farmer.nes",$10,$4000
Game0200_e:
Game0204:
.incbin "CAT_GAMES\1_GAMES\Transmission.nes",$10,$4000
Game0204_e:
Game0205:
.incbin "CAT_GAMES\1_GAMES\Triple Jump.nes",$10,$4000
Game0205_e:
Game0207:
.incbin "CAT_GAMES\1_GAMES\Turtles.nes",$10,$4000
Game0207_e:
Game0208:
.incbin "CAT_GAMES\1_GAMES\Twin Cards.nes",$10,$4000
Game0208_e:
Game0209:
.incbin "CAT_GAMES\1_GAMES\Twin Fish.nes",$10,$4000
Game0209_e:
Game0210:
.incbin "CAT_GAMES\1_GAMES\UFO Race.nes",$10,$4000
Game0210_e:
.segment "ROM13"
Game0091:
.incbin "CAT_GAMES\1_GAMES\Future Tank.nes",$10,$4000
Game0091_e:
Game0092:
.incbin "CAT_GAMES\1_GAMES\Gallagant.nes",$10,$4000
Game0092_e:
Game0093:
.incbin "CAT_GAMES\1_GAMES\Garden War.nes",$10,$4000
Game0093_e:
Game0095:
.incbin "CAT_GAMES\1_GAMES\Goblet Tower.nes",$10,$4000
Game0095_e:
Game0097:
.incbin "CAT_GAMES\1_GAMES\Goodhand.nes",$10,$4000
Game0097_e:
Game0100:
.incbin "CAT_GAMES\1_GAMES\Grot Kid.nes",$10,$4000
Game0100_e:
Game0101:
.incbin "CAT_GAMES\1_GAMES\Hallihoo.nes",$10,$4000
Game0101_e:
Game0103:
.incbin "CAT_GAMES\1_GAMES\Happy Adventure.nes",$10,$4000
Game0103_e:
Game0105:
.incbin "CAT_GAMES\1_GAMES\Hassle.nes",$10,$4000
Game0105_e:
Game0106:
.incbin "CAT_GAMES\1_GAMES\Hexapod War.nes",$10,$4000
Game0106_e:
Game0107:
.incbin "CAT_GAMES\1_GAMES\High Jump.nes",$10,$4000
Game0107_e:
Game0109:
.incbin "CAT_GAMES\1_GAMES\Hit-Mouse.nes",$10,$4000
Game0109_e:
Game0110:
.incbin "CAT_GAMES\1_GAMES\Hoodle.nes",$10,$4000
Game0110_e:
Game0111:
.incbin "CAT_GAMES\1_GAMES\Hot Speed.nes",$10,$4000
Game0111_e:
Game0116:
.incbin "CAT_GAMES\1_GAMES\Javelin Throw.nes",$10,$4000
Game0116_e:
Game0119:
.incbin "CAT_GAMES\1_GAMES\Jungly Guy.nes",$10,$4000
Game0119_e:
Game0120:
.incbin "CAT_GAMES\1_GAMES\Labyrinth.nes",$10,$4000
Game0120_e:
Game0123:
.incbin "CAT_GAMES\1_GAMES\Levin Action.nes",$10,$4000
Game0123_e:
Game0126:
.incbin "CAT_GAMES\1_GAMES\Long Jump.nes",$10,$4000
Game0126_e:
Game0127:
.incbin "CAT_GAMES\1_GAMES\Lunarian.nes",$10,$4000
Game0127_e:
Game0128:
.incbin "CAT_GAMES\1_GAMES\Lunation.nes",$10,$4000
Game0128_e:
Game0129:
.incbin "CAT_GAMES\1_GAMES\Mad Xmas.nes",$10,$4000
Game0129_e:
Game0130:
.incbin "CAT_GAMES\1_GAMES\Magic Bubble.nes",$10,$4000
Game0130_e:
Game0132:
.incbin "CAT_GAMES\1_GAMES\Man in Red.nes",$10,$4000
Game0132_e:
Game0133:
.incbin "CAT_GAMES\1_GAMES\Mars.nes",$10,$4000
Game0133_e:
Game0138:
.incbin "CAT_GAMES\1_GAMES\Memory Test.nes",$10,$4000
Game0138_e:
Game0140:
.incbin "CAT_GAMES\1_GAMES\Motoboat.nes",$10,$4000
Game0140_e:
Game0143:
.incbin "CAT_GAMES\1_GAMES\Move Box.nes",$10,$4000
Game0143_e:
Game0148:
.incbin "CAT_GAMES\1_GAMES\Panzer Attack.nes",$10,$4000
Game0148_e:
Game0150:
.incbin "CAT_GAMES\1_GAMES\Patternmaker.nes",$10,$4000
Game0150_e:
Game0151:
.incbin "CAT_GAMES\1_GAMES\Penguin.nes",$10,$4000
Game0151_e:
Game0153:
.incbin "CAT_GAMES\1_GAMES\Pobble.nes",$10,$4000
Game0153_e:
.segment "ROM14"
Game0037:
.incbin "CAT_GAMES\1_GAMES\BugBear.nes",$10,$4000
Game0037_e:
Game0038:
.incbin "CAT_GAMES\1_GAMES\Build Pillars.nes",$10,$4000
Game0038_e:
Game0039:
.incbin "CAT_GAMES\1_GAMES\Burrow.nes",$10,$4000
Game0039_e:
Game0042:
.incbin "CAT_GAMES\1_GAMES\Cannonade.nes",$10,$4000
Game0042_e:
Game0043:
.incbin "CAT_GAMES\1_GAMES\Care Bear.nes",$10,$4000
Game0043_e:
Game0045:
.incbin "CAT_GAMES\1_GAMES\Close Quarters.nes",$10,$4000
Game0045_e:
Game0046:
.incbin "CAT_GAMES\1_GAMES\Coast Guard.nes",$10,$4000
Game0046_e:
Game0047:
.incbin "CAT_GAMES\1_GAMES\Cobra of Sky.nes",$10,$4000
Game0047_e:
Game0048:
.incbin "CAT_GAMES\1_GAMES\Combata.nes",$10,$4000
Game0048_e:
Game0049:
.incbin "CAT_GAMES\1_GAMES\Conqueror.nes",$10,$4000
Game0049_e:
Game0053:
.incbin "CAT_GAMES\1_GAMES\Cub Adventure.nes",$10,$4000
Game0053_e:
Game0054:
.incbin "CAT_GAMES\1_GAMES\Dada.nes",$10,$4000
Game0054_e:
Game0056:
.incbin "CAT_GAMES\1_GAMES\Dark Castle.nes",$10,$4000
Game0056_e:
Game0057:
.incbin "CAT_GAMES\1_GAMES\Defensive.nes",$10,$4000
Game0057_e:
Game0060:
.incbin "CAT_GAMES\1_GAMES\Depth Bomb.nes",$10,$4000
Game0060_e:
Game0061:
.incbin "CAT_GAMES\1_GAMES\Devildom Doom.nes",$10,$4000
Game0061_e:
Game0062:
.incbin "CAT_GAMES\1_GAMES\Dice.nes",$10,$4000
Game0062_e:
Game0063:
.incbin "CAT_GAMES\1_GAMES\Discus Put.nes",$10,$4000
Game0063_e:
Game0064:
.incbin "CAT_GAMES\1_GAMES\Dominoes.nes",$10,$4000
Game0064_e:
Game0065:
.incbin "CAT_GAMES\1_GAMES\Dragon Den.nes",$10,$4000
Game0065_e:
Game0066:
.incbin "CAT_GAMES\1_GAMES\Dune War.nes",$10,$4000
Game0066_e:
Game0067:
.incbin "CAT_GAMES\1_GAMES\Edacity Snakes.nes",$10,$4000
Game0067_e:
Game0074:
.incbin "CAT_GAMES\1_GAMES\Falling.nes",$10,$4000
Game0074_e:
Game0078:
.incbin "CAT_GAMES\1_GAMES\Firebase.nes",$10,$4000
Game0078_e:
Game0079:
.incbin "CAT_GAMES\1_GAMES\First Defender.nes",$10,$4000
Game0079_e:
Game0081:
.incbin "CAT_GAMES\1_GAMES\Fish War.nes",$10,$4000
Game0081_e:
Game0082:
.incbin "CAT_GAMES\1_GAMES\Fisher.nes",$10,$4000
Game0082_e:
Game0083:
.incbin "CAT_GAMES\1_GAMES\Five Days.nes",$10,$4000
Game0083_e:
Game0086:
.incbin "CAT_GAMES\1_GAMES\Frantic Mouse.nes",$10,$4000
Game0086_e:
Game0087:
.incbin "CAT_GAMES\1_GAMES\Freecell.nes",$10,$4000
Game0087_e:
Game0088:
.incbin "CAT_GAMES\1_GAMES\Fruit Dish.nes",$10,$4000
Game0088_e:
Game0089:
.incbin "CAT_GAMES\1_GAMES\Fruit Gift.nes",$10,$4000
Game0089_e:
.segment "ROM15"
Game0002:
.incbin "CAT_GAMES\1_GAMES\100m Dash.nes",$10,$4000
Game0002_e:
Game0003:
.incbin "CAT_GAMES\1_GAMES\110m Hurdles.nes",$10,$4000
Game0003_e:
Game0006:
.incbin "CAT_GAMES\1_GAMES\Aether.nes",$10,$4000
Game0006_e:
Game0008:
.incbin "CAT_GAMES\1_GAMES\Aimless.nes",$10,$4000
Game0008_e:
Game0012:
.incbin "CAT_GAMES\1_GAMES\Angel.nes",$10,$4000
Game0012_e:
Game0015:
.incbin "CAT_GAMES\1_GAMES\Antiquarium.nes",$10,$4000
Game0015_e:
Game0016:
.incbin "CAT_GAMES\1_GAMES\Apple Chess.nes",$10,$4000
Game0016_e:
Game0017:
.incbin "CAT_GAMES\1_GAMES\Archery.nes",$10,$4000
Game0017_e:
Game0018:
.incbin "CAT_GAMES\1_GAMES\Arena.nes",$10,$4000
Game0018_e:
Game0019:
.incbin "CAT_GAMES\1_GAMES\Assart.nes",$10,$4000
Game0019_e:
Game0020:
.incbin "CAT_GAMES\1_GAMES\Awful Rushing.nes",$10,$4000
Game0020_e:
Game0022:
.incbin "CAT_GAMES\1_GAMES\Bandits.nes",$10,$4000
Game0022_e:
Game0023:
.incbin "CAT_GAMES\1_GAMES\Baseball.nes",$10,$4000
Game0023_e:
Game0026:
.incbin "CAT_GAMES\1_GAMES\Billiards.nes",$10,$4000
Game0026_e:
Game0027:
.incbin "CAT_GAMES\1_GAMES\Bitha.nes",$10,$4000
Game0027_e:
Game0029:
.incbin "CAT_GAMES\1_GAMES\Boat Race 1.nes",$10,$4000
Game0029_e:
Game0031:
.incbin "CAT_GAMES\1_GAMES\Bomb King.nes",$10,$4000
Game0031_e:
Game0032:
.incbin "CAT_GAMES\1_GAMES\Bounce.nes",$10,$4000
Game0032_e:
Game0034:
.incbin "CAT_GAMES\1_GAMES\Bubble.nes",$10,$4000
Game0034_e:

.segment "ROM_OFFS"
dw Game_0001
dw Game_0002
dw Game_0003
dw Game_0004
dw Game_0005
dw Game_0006
dw Game_0007
dw Game_0008
dw Game_0009
dw Game_0010
dw Game_0011
dw Game_0012
dw Game_0013
dw Game_0014
dw Game_0015
dw Game_0016
dw Game_0017
dw Game_0018
dw Game_0019
dw Game_0020
dw Game_0021
dw Game_0022
dw Game_0023
dw Game_0024
dw Game_0025
dw Game_0026
dw Game_0027
dw Game_0028
dw Game_0029
dw Game_0030
dw Game_0031
dw Game_0032
dw Game_0033
dw Game_0034
dw Game_0035
dw Game_0036
dw Game_0037
dw Game_0038
dw Game_0039
dw Game_0040
dw Game_0041
dw Game_0042
dw Game_0043
dw Game_0044
dw Game_0045
dw Game_0046
dw Game_0047
dw Game_0048
dw Game_0049
dw Game_0050
dw Game_0051
dw Game_0052
dw Game_0053
dw Game_0054
dw Game_0055
dw Game_0056
dw Game_0057
dw Game_0058
dw Game_0059
dw Game_0060
dw Game_0061
dw Game_0062
dw Game_0063
dw Game_0064
dw Game_0065
dw Game_0066
dw Game_0067
dw Game_0068
dw Game_0069
dw Game_0070
dw Game_0071
dw Game_0072
dw Game_0073
dw Game_0074
dw Game_0075
dw Game_0076
dw Game_0077
dw Game_0078
dw Game_0079
dw Game_0080
dw Game_0081
dw Game_0082
dw Game_0083
dw Game_0084
dw Game_0085
dw Game_0086
dw Game_0087
dw Game_0088
dw Game_0089
dw Game_0090
dw Game_0091
dw Game_0092
dw Game_0093
dw Game_0094
dw Game_0095
dw Game_0096
dw Game_0097
dw Game_0098
dw Game_0099
dw Game_0100
dw Game_0101
dw Game_0102
dw Game_0103
dw Game_0104
dw Game_0105
dw Game_0106
dw Game_0107
dw Game_0108
dw Game_0109
dw Game_0110
dw Game_0111
dw Game_0112
dw Game_0113
dw Game_0114
dw Game_0115
dw Game_0116
dw Game_0117
dw Game_0118
dw Game_0119
dw Game_0120
dw Game_0121
dw Game_0122
dw Game_0123
dw Game_0124
dw Game_0125
dw Game_0126
dw Game_0127
dw Game_0128
dw Game_0129
dw Game_0130
dw Game_0131
dw Game_0132
dw Game_0133
dw Game_0134
dw Game_0135
dw Game_0136
dw Game_0137
dw Game_0138
dw Game_0139
dw Game_0140
dw Game_0141
dw Game_0142
dw Game_0143
dw Game_0144
dw Game_0145
dw Game_0146
dw Game_0147
dw Game_0148
dw Game_0149
dw Game_0150
dw Game_0151
dw Game_0152
dw Game_0153
dw Game_0154
dw Game_0155
dw Game_0156
dw Game_0157
dw Game_0158
dw Game_0159
dw Game_0160
dw Game_0161
dw Game_0162
dw Game_0163
dw Game_0164
dw Game_0165
dw Game_0166
dw Game_0167
dw Game_0168
dw Game_0169
dw Game_0170
dw Game_0171
dw Game_0172
dw Game_0173
dw Game_0174
dw Game_0175
dw Game_0176
dw Game_0177
dw Game_0178
dw Game_0179
dw Game_0180
dw Game_0181
dw Game_0182
dw Game_0183
dw Game_0184
dw Game_0185
dw Game_0186
dw Game_0187
dw Game_0188
dw Game_0189
dw Game_0190
dw Game_0191
dw Game_0192
dw Game_0193
dw Game_0194
dw Game_0195
dw Game_0196
dw Game_0197
dw Game_0198
dw Game_0199
dw Game_0200
dw Game_0201
dw Game_0202
dw Game_0203
dw Game_0204
dw Game_0205
dw Game_0206
dw Game_0207
dw Game_0208
dw Game_0209
dw Game_0210
dw Game_0211
dw Game_0212
dw Game_0213
dw Game_0214
dw Game_0215
dw Game_0216
dw Game_0217
dw Game_0218
dw Game_0219
dw Game_0220
dw Game_0221
dw Game_0222
dw Game_0223

.segment "MENU_GAME_DATA_1"
Game_0001:
db 1
gametable Game0001,Game0001_e,Game0001_c,Game0001_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0001_c,0

Game_0002:
db 1
gametable Game0002,Game0002_e,Game0002_c,Game0002_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0002_c,0

Game_0003:
db 1
gametable Game0003,Game0003_e,Game0003_c,Game0003_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0003_c,0

Game_0004:
db 1
gametable Game0004,Game0004_e,Game0004_c,Game0004_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0004_c,0

Game_0005:
db 1
gametable Game0005,Game0005_e,Game0005_c,Game0005_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0005_c,0

Game_0006:
db 1
gametable Game0006,Game0006_e,Game0006_c,Game0006_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0006_c,0

Game_0007:
db 1
gametable Game0007,Game0007_e,Game0007_c,Game0007_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0007_c,0

Game_0008:
db 1
gametable Game0008,Game0008_e,Game0008_c,Game0008_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0008_c,0

Game_0009:
db 1
gametable Game0009,Game0009_e,Game0009_c,Game0009_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0009_c,0

Game_0010:
db 1
gametable Game0010,Game0010_e,Game0010_c,Game0010_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0010_c,0

Game_0011:
db 1
gametable Game0011,Game0011_e,Game0011_c,Game0011_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0011_c,0

Game_0012:
db 1
gametable Game0012,Game0012_e,Game0012_c,Game0012_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0012_c,0

Game_0013:
db 1
gametable Game0013,Game0013_e,Game0013_c,Game0013_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0013_c,0

Game_0014:
db 0
gametable Game0014,Game0014_e,Game0014_c,Game0014_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0014_c,0

Game_0015:
db 1
gametable Game0015,Game0015_e,Game0015_c,Game0015_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0015_c,0

Game_0016:
db 1
gametable Game0016,Game0016_e,Game0016_c,Game0016_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0016_c,0

Game_0017:
db 1
gametable Game0017,Game0017_e,Game0017_c,Game0017_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0017_c,0

Game_0018:
db 1
gametable Game0018,Game0018_e,Game0018_c,Game0018_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0018_c,0

Game_0019:
db 1
gametable Game0019,Game0019_e,Game0019_c,Game0019_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0019_c,0

Game_0020:
db 0
gametable Game0020,Game0020_e,Game0020_c,Game0020_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0020_c,0

Game_0021:
db 1
gametable Game0021,Game0021_e,Game0021_c,Game0021_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0021_c,0

Game_0022:
db 0
gametable Game0022,Game0022_e,Game0022_c,Game0022_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0022_c,0

Game_0023:
db 1
gametable Game0023,Game0023_e,Game0023_c,Game0023_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0023_c,0

Game_0024:
db 1
gametable Game0024,Game0024_e,Game0024_c,Game0024_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0024_c,0

Game_0025:
db 0
gametable Game0025,Game0025_e,Game0025_c,Game0025_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0025_c,0

Game_0026:
db 0
gametable Game0026,Game0026_e,Game0026_c,Game0026_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0026_c,0

Game_0027:
db 0
gametable Game0027,Game0027_e,Game0027_c,Game0027_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0027_c,0

Game_0028:
db 0
gametable Game0028,Game0028_e,Game0028_c,Game0028_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0028_c,0

Game_0029:
db 0
gametable Game0029,Game0029_e,Game0029_c,Game0029_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0029_c,0

Game_0030:
db 1
gametable Game0030,Game0030_e,Game0030_c,Game0030_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0030_c,0

Game_0031:
db 1
gametable Game0031,Game0031_e,Game0031_c,Game0031_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0031_c,0

Game_0032:
db 0
gametable Game0032,Game0032_e,Game0032_c,Game0032_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0032_c,0

Game_0033:
db 1
gametable Game0033,Game0033_e,Game0033_c,Game0033_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0033_c,0

Game_0034:
db 1
gametable Game0034,Game0034_e,Game0034_c,Game0034_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0034_c,0

Game_0035:
db 1
gametable Game0035,Game0035_e,Game0035_c,Game0035_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0035_c,0

Game_0036:
db 1
gametable Game0036,Game0036_e,Game0036_c,Game0036_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0036_c,0

Game_0037:
db 1
gametable Game0037,Game0037_e,Game0037_c,Game0037_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0037_c,0

Game_0038:
db 1
gametable Game0038,Game0038_e,Game0038_c,Game0038_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0038_c,0

Game_0039:
db 1
gametable Game0039,Game0039_e,Game0039_c,Game0039_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0039_c,0

Game_0040:
db 1
gametable Game0040,Game0040_e,Game0040_c,Game0040_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0040_c,0

Game_0041:
db 1
gametable Game0041,Game0041_e,Game0041_c,Game0041_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0041_c,0

Game_0042:
db 1
gametable Game0042,Game0042_e,Game0042_c,Game0042_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0042_c,0

Game_0043:
db 1
gametable Game0043,Game0043_e,Game0043_c,Game0043_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0043_c,0

Game_0044:
db 1
gametable Game0044,Game0044_e,Game0044_c,Game0044_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0044_c,0

Game_0045:
db 1
gametable Game0045,Game0045_e,Game0045_c,Game0045_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0045_c,0

Game_0046:
db 1
gametable Game0046,Game0046_e,Game0046_c,Game0046_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0046_c,0

Game_0047:
db 0
gametable Game0047,Game0047_e,Game0047_c,Game0047_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0047_c,0

Game_0048:
db 1
gametable Game0048,Game0048_e,Game0048_c,Game0048_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0048_c,0

Game_0049:
db 0
gametable Game0049,Game0049_e,Game0049_c,Game0049_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0049_c,0

Game_0050:
db 1
gametable Game0050,Game0050_e,Game0050_c,Game0050_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0050_c,0

Game_0051:
db 1
gametable Game0051,Game0051_e,Game0051_c,Game0051_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0051_c,0

Game_0052:
db 1
gametable Game0052,Game0052_e,Game0052_c,Game0052_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0052_c,0

Game_0053:
db 1
gametable Game0053,Game0053_e,Game0053_c,Game0053_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0053_c,0

Game_0054:
db 1
gametable Game0054,Game0054_e,Game0054_c,Game0054_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0054_c,0

Game_0055:
db 1
gametable Game0055,Game0055_e,Game0055_c,Game0055_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0055_c,0

Game_0056:
db 1
gametable Game0056,Game0056_e,Game0056_c,Game0056_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0056_c,0

Game_0057:
db 1
gametable Game0057,Game0057_e,Game0057_c,Game0057_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0057_c,0

Game_0058:
db 1
gametable Game0058,Game0058_e,Game0058_c,Game0058_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0058_c,0

Game_0059:
db 0
gametable Game0059,Game0059_e,Game0059_c,Game0059_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0059_c,0

Game_0060:
db 1
gametable Game0060,Game0060_e,Game0060_c,Game0060_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0060_c,0

Game_0061:
db 1
gametable Game0061,Game0061_e,Game0061_c,Game0061_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0061_c,0

Game_0062:
db 1
gametable Game0062,Game0062_e,Game0062_c,Game0062_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0062_c,0

Game_0063:
db 1
gametable Game0063,Game0063_e,Game0063_c,Game0063_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0063_c,0

Game_0064:
db 1
gametable Game0064,Game0064_e,Game0064_c,Game0064_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0064_c,0

Game_0065:
db 1
gametable Game0065,Game0065_e,Game0065_c,Game0065_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0065_c,0

Game_0066:
db 1
gametable Game0066,Game0066_e,Game0066_c,Game0066_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0066_c,0

Game_0067:
db 1
gametable Game0067,Game0067_e,Game0067_c,Game0067_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0067_c,0

Game_0068:
db 1
gametable Game0068,Game0068_e,Game0068_c,Game0068_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0068_c,0

Game_0069:
db 1
gametable Game0069,Game0069_e,Game0069_c,Game0069_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0069_c,0

Game_0070:
db 1
gametable Game0070,Game0070_e,Game0070_c,Game0070_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0070_c,0

Game_0071:
db 1
gametable Game0071,Game0071_e,Game0071_c,Game0071_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0071_c,0

Game_0072:
db 1
gametable Game0072,Game0072_e,Game0072_c,Game0072_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0072_c,0

Game_0073:
db 1
gametable Game0073,Game0073_e,Game0073_c,Game0073_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0073_c,0

Game_0074:
db 1
gametable Game0074,Game0074_e,Game0074_c,Game0074_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0074_c,0

Game_0075:
db 1
gametable Game0075,Game0075_e,Game0075_c,Game0075_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0075_c,0

Game_0076:
db 1
gametable Game0076,Game0076_e,Game0076_c,Game0076_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0076_c,0

Game_0077:
db 1
gametable Game0077,Game0077_e,Game0077_c,Game0077_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0077_c,0

Game_0078:
db 1
gametable Game0078,Game0078_e,Game0078_c,Game0078_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0078_c,0

Game_0079:
db 1
gametable Game0079,Game0079_e,Game0079_c,Game0079_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0079_c,0

Game_0080:
db 0
gametable Game0080,Game0080_e,Game0080_c,Game0080_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0080_c,0

Game_0081:
db 1
gametable Game0081,Game0081_e,Game0081_c,Game0081_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0081_c,0

Game_0082:
db 1
gametable Game0082,Game0082_e,Game0082_c,Game0082_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0082_c,0

Game_0083:
db 1
gametable Game0083,Game0083_e,Game0083_c,Game0083_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0083_c,0

Game_0084:
db 1
gametable Game0084,Game0084_e,Game0084_c,Game0084_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0084_c,0

Game_0085:
db 1
gametable Game0085,Game0085_e,Game0085_c,Game0085_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0085_c,0

Game_0086:
db 1
gametable Game0086,Game0086_e,Game0086_c,Game0086_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0086_c,0

Game_0087:
db 1
gametable Game0087,Game0087_e,Game0087_c,Game0087_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0087_c,0

Game_0088:
db 1
gametable Game0088,Game0088_e,Game0088_c,Game0088_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0088_c,0

Game_0089:
db 1
gametable Game0089,Game0089_e,Game0089_c,Game0089_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0089_c,0

Game_0090:
db 1
gametable Game0090,Game0090_e,Game0090_c,Game0090_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0090_c,0

Game_0091:
db 0
gametable Game0091,Game0091_e,Game0091_c,Game0091_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0091_c,0

Game_0092:
db 1
gametable Game0092,Game0092_e,Game0092_c,Game0092_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0092_c,0

Game_0093:
db 0
gametable Game0093,Game0093_e,Game0093_c,Game0093_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0093_c,0

Game_0094:
db 1
gametable Game0094,Game0094_e,Game0094_c,Game0094_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0094_c,0

Game_0095:
db 0
gametable Game0095,Game0095_e,Game0095_c,Game0095_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0095_c,0

Game_0096:
db 1
gametable Game0096,Game0096_e,Game0096_c,Game0096_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0096_c,0

Game_0097:
db 0
gametable Game0097,Game0097_e,Game0097_c,Game0097_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0097_c,0

Game_0098:
db 0
gametable Game0098,Game0098_e,Game0098_c,Game0098_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0098_c,0

Game_0099:
db 1
gametable Game0099,Game0099_e,Game0099_c,Game0099_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0099_c,0

Game_0100:
db 1
gametable Game0100,Game0100_e,Game0100_c,Game0100_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0100_c,0

Game_0101:
db 1
gametable Game0101,Game0101_e,Game0101_c,Game0101_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0101_c,0

Game_0102:
db 1
gametable Game0102,Game0102_e,Game0102_c,Game0102_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0102_c,0

Game_0103:
db 1
gametable Game0103,Game0103_e,Game0103_c,Game0103_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0103_c,0

Game_0104:
db 1
gametable Game0104,Game0104_e,Game0104_c,Game0104_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0104_c,0

Game_0105:
db 1
gametable Game0105,Game0105_e,Game0105_c,Game0105_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0105_c,0

Game_0106:
db 1
gametable Game0106,Game0106_e,Game0106_c,Game0106_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0106_c,0

Game_0107:
db 1
gametable Game0107,Game0107_e,Game0107_c,Game0107_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0107_c,0

Game_0108:
db 0
gametable Game0108,Game0108_e,Game0108_c,Game0108_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0108_c,0

Game_0109:
db 1
gametable Game0109,Game0109_e,Game0109_c,Game0109_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0109_c,0

Game_0110:
db 1
gametable Game0110,Game0110_e,Game0110_c,Game0110_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0110_c,0

Game_0111:
db 1
gametable Game0111,Game0111_e,Game0111_c,Game0111_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0111_c,0

Game_0112:
db 0
gametable Game0112,Game0112_e,Game0112_c,Game0112_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0112_c,0

Game_0113:
db 0
gametable Game0113,Game0113_e,Game0113_c,Game0113_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0113_c,0

Game_0114:
db 0
gametable Game0114,Game0114_e,Game0114_c,Game0114_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0114_c,0

Game_0115:
db 1
gametable Game0115,Game0115_e,Game0115_c,Game0115_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0115_c,0

Game_0116:
db 1
gametable Game0116,Game0116_e,Game0116_c,Game0116_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0116_c,0

Game_0117:
db 1
gametable Game0117,Game0117_e,Game0117_c,Game0117_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0117_c,0

Game_0118:
db 0
gametable Game0118,Game0118_e,Game0118_c,Game0118_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0118_c,0

Game_0119:
db 1
gametable Game0119,Game0119_e,Game0119_c,Game0119_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0119_c,0

Game_0120:
db 1
gametable Game0120,Game0120_e,Game0120_c,Game0120_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0120_c,0

Game_0121:
db 1
gametable Game0121,Game0121_e,Game0121_c,Game0121_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0121_c,0

Game_0122:
db 1
gametable Game0122,Game0122_e,Game0122_c,Game0122_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0122_c,0

Game_0123:
db 0
gametable Game0123,Game0123_e,Game0123_c,Game0123_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0123_c,0

Game_0124:
db 1
gametable Game0124,Game0124_e,Game0124_c,Game0124_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0124_c,0

Game_0125:
db 1
gametable Game0125,Game0125_e,Game0125_c,Game0125_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0125_c,0

Game_0126:
db 1
gametable Game0126,Game0126_e,Game0126_c,Game0126_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0126_c,0

Game_0127:
db 1
gametable Game0127,Game0127_e,Game0127_c,Game0127_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0127_c,0

Game_0128:
db 1
gametable Game0128,Game0128_e,Game0128_c,Game0128_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0128_c,0

Game_0129:
db 1
gametable Game0129,Game0129_e,Game0129_c,Game0129_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0129_c,0

Game_0130:
db 0
gametable Game0130,Game0130_e,Game0130_c,Game0130_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0130_c,0

Game_0131:
db 1
gametable Game0131,Game0131_e,Game0131_c,Game0131_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0131_c,0

Game_0132:
db 0
gametable Game0132,Game0132_e,Game0132_c,Game0132_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0132_c,0

Game_0133:
db 0
gametable Game0133,Game0133_e,Game0133_c,Game0133_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0133_c,0

Game_0134:
db 1
gametable Game0134,Game0134_e,Game0134_c,Game0134_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0134_c,0

Game_0135:
db 0
gametable Game0135,Game0135_e,Game0135_c,Game0135_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0135_c,0

Game_0136:
db 1
gametable Game0136,Game0136_e,Game0136_c,Game0136_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0136_c,0

Game_0137:
db 1
gametable Game0137,Game0137_e,Game0137_c,Game0137_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0137_c,0

Game_0138:
db 1
gametable Game0138,Game0138_e,Game0138_c,Game0138_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0138_c,0

Game_0139:
db 1
gametable Game0139,Game0139_e,Game0139_c,Game0139_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0139_c,0

Game_0140:
db 1
gametable Game0140,Game0140_e,Game0140_c,Game0140_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0140_c,0

Game_0141:
db 1
gametable Game0141,Game0141_e,Game0141_c,Game0141_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0141_c,0

Game_0142:
db 0
gametable Game0142,Game0142_e,Game0142_c,Game0142_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0142_c,0

Game_0143:
db 0
gametable Game0143,Game0143_e,Game0143_c,Game0143_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0143_c,0

Game_0144:
db 1
gametable Game0144,Game0144_e,Game0144_c,Game0144_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0144_c,0

Game_0145:
db 1
gametable Game0145,Game0145_e,Game0145_c,Game0145_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0145_c,0

Game_0146:
db 1
gametable Game0146,Game0146_e,Game0146_c,Game0146_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0146_c,0

Game_0147:
db 1
gametable Game0147,Game0147_e,Game0147_c,Game0147_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0147_c,0

Game_0148:
db 1
gametable Game0148,Game0148_e,Game0148_c,Game0148_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0148_c,0

Game_0149:
db 1
gametable Game0149,Game0149_e,Game0149_c,Game0149_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0149_c,0

Game_0150:
db 1
gametable Game0150,Game0150_e,Game0150_c,Game0150_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0150_c,0

Game_0151:
db 1
gametable Game0151,Game0151_e,Game0151_c,Game0151_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0151_c,0

Game_0152:
db 1
gametable Game0152,Game0152_e,Game0152_c,Game0152_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0152_c,0

Game_0153:
db 1
gametable Game0153,Game0153_e,Game0153_c,Game0153_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0153_c,0

Game_0154:
db 1
gametable Game0154,Game0154_e,Game0154_c,Game0154_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0154_c,0

Game_0155:
db 1
gametable Game0155,Game0155_e,Game0155_c,Game0155_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0155_c,0

Game_0156:
db 1
gametable Game0156,Game0156_e,Game0156_c,Game0156_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0156_c,0

Game_0157:
db 1
gametable Game0157,Game0157_e,Game0157_c,Game0157_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0157_c,0

Game_0158:
db 1
gametable Game0158,Game0158_e,Game0158_c,Game0158_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0158_c,0

Game_0159:
db 1
gametable Game0159,Game0159_e,Game0159_c,Game0159_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0159_c,0

Game_0160:
db 1
gametable Game0160,Game0160_e,Game0160_c,Game0160_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0160_c,0

Game_0161:
db 1
gametable Game0161,Game0161_e,Game0161_c,Game0161_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0161_c,0

Game_0162:
db 0
gametable Game0162,Game0162_e,Game0162_c,Game0162_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0162_c,0

Game_0163:
db 1
gametable Game0163,Game0163_e,Game0163_c,Game0163_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0163_c,0

Game_0164:
db 0
gametable Game0164,Game0164_e,Game0164_c,Game0164_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0164_c,0

Game_0165:
db 1
gametable Game0165,Game0165_e,Game0165_c,Game0165_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0165_c,0

Game_0166:
db 1
gametable Game0166,Game0166_e,Game0166_c,Game0166_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0166_c,0

Game_0167:
db 1
gametable Game0167,Game0167_e,Game0167_c,Game0167_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0167_c,0

Game_0168:
db 1
gametable Game0168,Game0168_e,Game0168_c,Game0168_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0168_c,0

Game_0169:
db 1
gametable Game0169,Game0169_e,Game0169_c,Game0169_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0169_c,0

Game_0170:
db 1
gametable Game0170,Game0170_e,Game0170_c,Game0170_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0170_c,0

Game_0171:
db 1
gametable Game0171,Game0171_e,Game0171_c,Game0171_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0171_c,0

Game_0172:
db 0
gametable Game0172,Game0172_e,Game0172_c,Game0172_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0172_c,0

Game_0173:
db 0
gametable Game0173,Game0173_e,Game0173_c,Game0173_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0173_c,0

Game_0174:
db 1
gametable Game0174,Game0174_e,Game0174_c,Game0174_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0174_c,0

Game_0175:
db 1
gametable Game0175,Game0175_e,Game0175_c,Game0175_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0175_c,0

Game_0176:
db 0
gametable Game0176,Game0176_e,Game0176_c,Game0176_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0176_c,0

Game_0177:
db 1
gametable Game0177,Game0177_e,Game0177_c,Game0177_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0177_c,0

Game_0178:
db 1
gametable Game0178,Game0178_e,Game0178_c,Game0178_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0178_c,0

Game_0179:
db 1
gametable Game0179,Game0179_e,Game0179_c,Game0179_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0179_c,0

Game_0180:
db 1
gametable Game0180,Game0180_e,Game0180_c,Game0180_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0180_c,0

Game_0181:
db 0
gametable Game0181,Game0181_e,Game0181_c,Game0181_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0181_c,0

Game_0182:
db 1
gametable Game0182,Game0182_e,Game0182_c,Game0182_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0182_c,0

Game_0183:
db 1
gametable Game0183,Game0183_e,Game0183_c,Game0183_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0183_c,0

Game_0184:
db 0
gametable Game0184,Game0184_e,Game0184_c,Game0184_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0184_c,0

Game_0185:
db 0
gametable Game0185,Game0185_e,Game0185_c,Game0185_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0185_c,0

Game_0186:
db 1
gametable Game0186,Game0186_e,Game0186_c,Game0186_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0186_c,0

Game_0187:
db 0
gametable Game0187,Game0187_e,Game0187_c,Game0187_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0187_c,0

Game_0188:
db 1
gametable Game0188,Game0188_e,Game0188_c,Game0188_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0188_c,0

Game_0189:
db 1
gametable Game0189,Game0189_e,Game0189_c,Game0189_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0189_c,0

Game_0190:
db 0
gametable Game0190,Game0190_e,Game0190_c,Game0190_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0190_c,0

Game_0191:
db 1
gametable Game0191,Game0191_e,Game0191_c,Game0191_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0191_c,0

Game_0192:
db 1
gametable Game0192,Game0192_e,Game0192_c,Game0192_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0192_c,0

Game_0193:
db 1
gametable Game0193,Game0193_e,Game0193_c,Game0193_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0193_c,0

Game_0194:
db 1
gametable Game0194,Game0194_e,Game0194_c,Game0194_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0194_c,0

Game_0195:
db 0
gametable Game0195,Game0195_e,Game0195_c,Game0195_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0195_c,0

Game_0196:
db 1
gametable Game0196,Game0196_e,Game0196_c,Game0196_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0196_c,0

Game_0197:
db 1
gametable Game0197,Game0197_e,Game0197_c,Game0197_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0197_c,0

Game_0198:
db 1
gametable Game0198,Game0198_e,Game0198_c,Game0198_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0198_c,0

Game_0199:
db 1
gametable Game0199,Game0199_e,Game0199_c,Game0199_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0199_c,0

Game_0200:
db 1
gametable Game0200,Game0200_e,Game0200_c,Game0200_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0200_c,0

Game_0201:
db 1
gametable Game0201,Game0201_e,Game0201_c,Game0201_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0201_c,0

Game_0202:
db 0
gametable Game0202,Game0202_e,Game0202_c,Game0202_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0202_c,0

Game_0203:
db 1
gametable Game0203,Game0203_e,Game0203_c,Game0203_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0203_c,0

Game_0204:
db 1
gametable Game0204,Game0204_e,Game0204_c,Game0204_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0204_c,0

Game_0205:
db 1
gametable Game0205,Game0205_e,Game0205_c,Game0205_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0205_c,0

Game_0206:
db 0
gametable Game0206,Game0206_e,Game0206_c,Game0206_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0206_c,0

Game_0207:
db 0
gametable Game0207,Game0207_e,Game0207_c,Game0207_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0207_c,0

Game_0208:
db 0
gametable Game0208,Game0208_e,Game0208_c,Game0208_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0208_c,0

Game_0209:
db 1
gametable Game0209,Game0209_e,Game0209_c,Game0209_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0209_c,0

Game_0210:
db 0
gametable Game0210,Game0210_e,Game0210_c,Game0210_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0210_c,0

Game_0211:
db 1
gametable Game0211,Game0211_e,Game0211_c,Game0211_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0211_c,0

Game_0212:
db 0
gametable Game0212,Game0212_e,Game0212_c,Game0212_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0212_c,0

Game_0213:
db 1
gametable Game0213,Game0213_e,Game0213_c,Game0213_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0213_c,0

Game_0214:
db 1
gametable Game0214,Game0214_e,Game0214_c,Game0214_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0214_c,0

Game_0215:
db 0
gametable Game0215,Game0215_e,Game0215_c,Game0215_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0215_c,0

Game_0216:
db 0
gametable Game0216,Game0216_e,Game0216_c,Game0216_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0216_c,0

Game_0217:
db 1
gametable Game0217,Game0217_e,Game0217_c,Game0217_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0217_c,0

Game_0218:
db 1
gametable Game0218,Game0218_e,Game0218_c,Game0218_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0218_c,0

Game_0219:
db 1
gametable Game0219,Game0219_e,Game0219_c,Game0219_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0219_c,0

Game_0220:
db 1
gametable Game0220,Game0220_e,Game0220_c,Game0220_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0220_c,0

Game_0221:
db 1
gametable Game0221,Game0221_e,Game0221_c,Game0221_c_e,0,0
dw LoadSub
db $0
bind_vrom Game0221_c,0

Game_0222:
db 1
gametable Game0222,Game0222_e,Game0222_c,Game0222_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0222_c,0

Game_0223:
db 1
gametable Game0223,Game0223_e,Game0223_c,Game0223_c_e,0,0
dw LoadSub
db $30
bind_vrom Game0223_c,0

